# pyproject.toml

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cdiutils"
version = "0.2.0"
description = "A Python package for (Bragg) Coherent X-ray Diffraction Imaging processing, analysis and visualisation workflows."
authors = [
    { name = "Clement Atlan", email = "c.atlan@outlook.com" }
]
urls = { "Homepage" = "https://github.com/clatlan/cdiutils" }
requires-python = ">=3.10"
readme = "README.md"

dependencies = [
    "colorcet>=3.0.0",
    "h5py>=3.6.0",
    "hdf5plugin>=3.2.0",
    "ipykernel",
    "matplotlib>=3.5.2",
    "numpy>=1.23.5",
    "pandas>=1.4.2",
    "paramiko>=2.12.0",
    "ruamel.yaml>=0.17.21",
    "ruamel.yaml.clib>=0.2.7",
    "scikit-image>=0.19.2",
    "scikit-learn>=1.1.3",
    "scipy>=1.8.0",
    "seaborn>=0.12.1",
    "silx>=1.0.0",
    "tabulate",
    "vtk>=9.0.1",
    "xrayutilities>=1.7.3",
    "ipyvolume",
    "ipython_genutils",
    "bokeh",
    "panel",
    "tornado",
]

[tool.setuptools]
packages = { find = {} }

[tool.setuptools.package-data]
"cdiutils" = [
    "process/pynx-id01cdi_template.slurm",
    "examples/bcdi_pipeline.ipynb",
    "examples/step_by_step_bcdi_analysis.ipynb"
]

[tool.setuptools.scripts]
scripts = [
    "scripts/prepare_bcdi_notebooks.py"
]
